services:
  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    ports:
      - "5000:80"
    restart: always
    networks:
      - backend
    depends_on:
      - db
      - redis

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?database user not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?database password not set}
      POSTGRES_DB: ${POSTGRES_DB:?database name not set}
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - backend
    restart: always

volumes:
  db_data:

networks:
  backend:
    driver: bridge
